package yaml

const (
	ERR_YAML_DIRECTIVE_ARGS     = "YAML directives must have exactly one argument"
	ERR_YAML_VERSION            = "bad YAML version: "
	ERR_YAML_MAJOR_VERSION      = "YAML major version too large"
	ERR_REPEATED_YAML_DIRECTIVE = "repeated YAML directive"
	ERR_TAG_DIRECTIVE_ARGS      = "TAG directives must have exactly two arguments"
	ERR_REPEATED_TAG_DIRECTIVE  = "repeated TAG directive"
	ERR_CHAR_IN_TAG_HANDLE      = "illegal character found while scanning tag handle"
	ERR_TAG_WITH_NO_SUFFIX      = "tag handle with no suffix"
	ERR_END_OF_VERBATIM_TAG     = "end of verbatim tag not found"
	ERR_END_OF_MAP              = "end of map not found"
	ERR_END_OF_MAP_FLOW         = "end of map flow not found"
	ERR_END_OF_SEQ              = "end of sequence not found"
	ERR_END_OF_SEQ_FLOW         = "end of sequence flow not found"
	ERR_MULTIPLE_TAGS           = "cannot assign multiple tags to the same node"
	ERR_MULTIPLE_ANCHORS        = "cannot assign multiple anchors to the same node"
	ERR_MULTIPLE_ALIASES        = "cannot assign multiple aliases to the same node"
	ERR_ALIAS_CONTENT           = "aliases can't have any content, *including* tags"
	ERR_INVALID_HEX             = "bad character found while scanning hex number"
	ERR_INVALID_UNICODE         = "invalid unicode: "
	ERR_INVALID_ESCAPE          = "unknown escape character: "
	ERR_UNKNOWN_TOKEN           = "unknown token"
	ERR_DOC_IN_SCALAR           = "illegal document indicator in scalar"
	ERR_EOF_IN_SCALAR           = "illegal EOF in scalar"
	ERR_CHAR_IN_SCALAR          = "illegal character in scalar"
	ERR_TAB_IN_INDENTATION      = "illegal tab when looking for indentation"
	ERR_FLOW_END                = "illegal flow end"
	ERR_BLOCK_ENTRY             = "illegal block entry"
	ERR_MAP_KEY                 = "illegal map key"
	ERR_MAP_VALUE               = "illegal map value"
	ERR_ALIAS_NOT_FOUND         = "alias not found after *"
	ERR_ANCHOR_NOT_FOUND        = "anchor not found after &"
	ERR_CHAR_IN_ALIAS           = "illegal character found while scanning alias"
	ERR_CHAR_IN_ANCHOR          = "illegal character found while scanning anchor"
	ERR_ZERO_INDENT_IN_BLOCK    = "cannot set zero indentation for a block scalar"
	ERR_CHAR_IN_BLOCK           = "unexpected character in block scalar"
	ERR_AMBIGUOUS_ANCHOR        = "cannot assign the same alias to multiple nodes"
	ERR_UNKNOWN_ANCHOR          = "the referenced anchor is not defined"

	ERR_INVALID_NODE    = "invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa"
	ERR_INVALID_SCALAR  = "invalid scalar"
	ERR_KEY_NOT_FOUND   = "key not found"
	ERR_BAD_CONVERSION  = "bad conversion"
	ERR_BAD_DEREFERENCE = "bad dereference"
	ERR_BAD_SUBSCRIPT   = "operator[] call on a scalar"
	ERR_BAD_PUSHBACK    = "appending to a non-sequence"
	ERR_BAD_INSERT      = "inserting in a non-convertible-to-map"

	ERR_UNMATCHED_GROUP_TAG = "unmatched group tag"
	ERR_UNEXPECTED_END_SEQ  = "unexpected end sequence token"
	ERR_UNEXPECTED_END_MAP  = "unexpected end map token"
	ERR_SINGLE_QUOTED_CHAR  = "invalid character in single-quoted string"
	ERR_INVALID_ANCHOR      = "invalid anchor"
	ERR_INVALID_ALIAS       = "invalid alias"
	ERR_INVALID_TAG         = "invalid tag"
	ERR_BAD_FILE            = "bad file"
)
